FROM gcr.io/google-appengine/python

RUN virtualenv --python=python3.7 /venv
ENV VIRTUAL_ENV /venv
ENV PATH /venv/bin:$PATH
ADD requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
ADD . /app

ENV PYTHONPATH=multitude
CMD ["uvicorn", "api:app"]
